# configuration for objects and agents, add scene as well
task_name: LongPipelineDelivery
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 
  primitives:
    - name: goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.1
        thickness: 0.00005  # 1e-5
        name: goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [3., -4.55, 0.9201]
      pos:
        ppos:
          p: [3., -4.55, 0.9201]
        qpos: [0.7071, 0., 0.7071, 0.]
        randp_scale: [0.1, 0.1, 0.]
        randq_scale: [0., 0., 0., 0.]
    
objects:
  -
    name: shoe
    file_path: assets/objects/single_shoe_annotated/base.glb
    annotation_path: assets/objects/single_shoe_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    collision:
      type: convex
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    pos:
      ppos:
        p: [2.98, -2.35, 0.962]
      qpos: [0.495, 0.498, 0.503, 0.505]
      randp_scale: [0.15, 0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 1
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  -
    robot_uid: panda_1
    pos:
      ppos:
        p: [2.35, -4.25, 0.92]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda_2
    pos:
      ppos:
        p: [2.35, -3.65, 0.92]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda_3
    pos:
      ppos:
        p: [2.35, -3.05, 0.92]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda_4
    pos:
      ppos:
        p: [2.35, -2.45, 0.92]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: pose
        params: [[3.426124, -4.21324, 1.232292], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent1
      pose:
        type: pose
        params: [[3.428001, -3.763242, 1.232343], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent2
      pose:
        type: pose
        params: [[3.429735, -2.963245, 1.23239], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent3
      pose:
        type: pose
        params: [[3.431468, -2.363248, 1.232436], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[3.963265, -3.3709376, 1.401497], [0.00358489, 0.0391521, 0.000140324, -0.999227]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: pose
        params: [[4.018396, -2.25305, 1.623708], [0.454605, 0.234498, 0.125406, -0.85007]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100