task_name: PlaceFood
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 

objects:
  -
    name: pot
    file_path: assets/objects/pot_annotated/mobility.urdf
    annotation_path: assets/objects/pot_annotated/model_data.json
    scale: 0.2
    pos:
      ppos:
        p: [2.4, -3.3, 1.]
      qpos: [0.732, 0.007, -0.009, 0.681]
      randp_scale: [0.3, 0., 0.]
      randq_scale: [0., 0., 0., 0.]
  -
    name: meat
    file_path: assets/objects/meat_annotated/textured.obj
    annotation_path: assets/objects/meat_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.5
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/meat_annotated/textured.obj
      scale: [0.08, 0.4, 0.08]
    collision:
      type: convex
      filename: assets/objects/meat_annotated/textured.obj
      scale: [0.08, 0.4, 0.08]
    pos:
      ppos:
        p: [2.45, -3.55, 0.921]
      qpos: [0.733, 0.082, -0.011, 0.675]
      randp_scale: [0.3, 0., 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.5
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  -
    robot_uid: panda-0
    pos:
      ppos:
        p: [2.55, -4.1, 0.92]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -2.3561944902, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-1
    pos:
      ppos:
        p: [2.55, -2.6, 0.92]
        q: [0., 0., -1.5707963268]
      qpos: [0., 0.3926990817, 0., -2.3561944902, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
  - 
    uid: head_camera_agent0
    pose:
      type: look_at
      params: [[2.05, -3.235, 1.32], [2.55, -3.585, 1.02]]
    width: 320
    height: 240
    fov: 1.5707963268
    near: 0.1
    far: 10
  - 
    uid: head_camera_agent1
    pose:
      type: look_at
      params: [[3.05, -3.465, 1.32], [2.55, -3.115, 1.02]]
    width: 320
    height: 240
    fov: 1.5707963268
    near: 0.1
    far: 10
  - 
    uid: head_camera_global
    pose:
      type: pose
      params: [[3.088897, -3.3171689, 1.6619], [0.00132558, -0.278757, 0.00042972, 0.960361]]
    width: 3840
    height: 2160
    fov: 1.5707963268
    near: 0.1
    far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[3.15, -2.65, 1.52], [2.55, -3.35, 1.27]]
      width: 3840
      height: 2160
      fov: 1
      near: 0.01
      far: 10