task_name: TakePhoto
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 
  primitives:
    - 
      name: cube
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.06
        color: [0.5, 0.5, 0.5, 1]
        name: cube
        body_type: static
        initial_pose:
          p: [2.5, -3.45, 0.95]
      pos:
        ppos:
          p: [2.5, -3.45, 0.95]
          q: [0., 0., 1.5707963268]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.1, 0.2, 0.]
        randq_scale: [0., 0., 0., 0.]
    
objects:
  -
    name: camera
    file_path: assets/objects/camera_annotated/textured.obj
    annotation_path: assets/objects/camera_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/camera_annotated/textured.obj
      scale: [0.25, 0.25, 0.25]
    collision:
      type: convex
      filename: assets/objects/camera_annotated/textured.obj
      scale: [0.25, 0.25, 0.25]
    pos:
      ppos:
        p: [2.5, -3.45, 1.009]
      qpos: [0.718, 0.012, 0.015, 0.696]
      randp_scale: [0.1, 0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.01
      cmass_local_pose: [0., 0., 0.]
      inertia: [0., 0., 0.]
  -
    name: meat
    file_path: assets/objects/meat_annotated/textured.obj
    annotation_path: assets/objects/meat_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/meat_annotated/textured.obj
      scale: [0.08, 0.4, 0.08]
    collision:
      type: convex
      filename: assets/objects/meat_annotated/textured.obj
      scale: [0.08, 0.4, 0.08]
    pos:
      ppos:
        p: [3, -3.75, 0.92]
      qpos: [0.014, 0.065, 0.052, 0.996]
      randp_scale: [0.15, 0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.005
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  -
    robot_uid: panda-0
    pos:
      ppos:
        p: [2.55, -4.2, 0.92]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-1
    pos:
      ppos:
        p: [2.55, -2.5, 0.92]
        q: [0., 0., -1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-2
    pos:
      ppos:
        p: [3.55, -3.35, 0.92]
        q: [0., 0., 3.1415926536]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-3
    pos:
      ppos:
        p: [1.95, -3.35, 0.92]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.1780972451, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: pose
        params: [[2.032621, -4.175534, 1.464694], [0.973373, -0.0263478, 0.148767, 0.172391]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_agent1
      pose:
        type: pose
        params: [[3.112348, -2.564296, 1.475279], [0.161394, 0.131976, 0.0217843, -0.977783]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_agent2
      pose:
        type: pose
        params: [[3.377632, -4.10711, 1.440754], [0.692724, -0.0746079, 0.0724179, 0.713668]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_agent3
      pose:
        type: pose
        params: [[1.84583, -2.891464, 1.526336], [0.871062, 0.053639, 0.0976719, -0.478366]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[3.222536, -4.144409, 1.614811], [0.42276, -0.258701, 0.127348, 0.859145]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 100
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[3.15, -2.65, 1.52], [2.55, -3.35, 1.27]]
      width: 3840
      height: 2160
      fov: 1
      near: 0.01
      far: 10