# configuration for objects and agents, add scene as well
task_name: TwoRobotsStackCube
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 
  primitives:
    - name: goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.11
        thickness: 0.00005  # 1e-5
        name: goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [2.6, -3.35, 0.921]

      pos:
        ppos:
          p: [2.6, -3.35, 0.921]
          q: [0., 1.5707963268, 0.]
        qpos: [0., 0.70710678, 0., 0.70710678]
        randp_scale: [0.1, 0., 0.]
        randq_scale: [0., 0., 0., 0.]

    - name: cubeA
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [0.04705882, 0.16470588, 0.62745098, 1.]
        name: cubeA
        initial_pose:
          p: [2.5, -3.45, 0.94]
      pos:
        ppos:
          p: [2.5, -3.45, 0.94]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.1, -0.1, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]

    - name: cubeB
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [0, 1, 0, 1]
        name: cubeB
        initial_pose:
          p: [2.5, -3.25, 0.94]
      pos:
        ppos:
          p: [2.5, -3.25, 0.94]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.1, 0.1, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]

agents:
  - robot_uid: panda-0
    pos:
      ppos:
        p: [2.55, -4.1, 0.92]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  - robot_uid: panda-1
    pos:
      ppos:
        p: [2.55, -2.6, 0.92]
        q: [0., 0., -1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: look_at
        params: [[2.05, -3.235, 1.32], [2.55, -3.585, 1.02]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
    - 
      uid: head_camera_agent1
      pose:
        type: look_at
        params: [[3.05, -3.465, 1.32], [2.55, -3.115, 1.02]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[3.103884, -3.2615069, 1.397073], [0.0190398, 0.183913, 0.00350626, -0.982752]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[3.95, -2.55, 1.67], [2.55, -3.25, 1.02]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100
