# configuration for objects and agents, add scene as well
task_name: LongPipelineDelivery
scene:
  name: Table
  env:
    floor_width: 100
  primitives:
    - name: goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.1
        thickness: 0.00005  # 1e-5
        name: goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [-0.15, -1.2, 0.0001]
      pos:
        ppos:
          p: [-0.15, -1.2, 0.0001]
        qpos: [0.7071, 0., 0.7071, 0.]
        randp_scale: [0.1, 0.1, 0.]
        randq_scale: [0., 0., 0., 0.]
  assets: 
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos: 
        ppos:
          p: [-0.12, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
    
objects:
  -
    name: shoe
    file_path: assets/objects/single_shoe_annotated/base.glb
    annotation_path: assets/objects/single_shoe_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    collision:
      type: convex
      filename: assets/objects/single_shoe_annotated/base.glb
      scale: [0.1, 0.1, 0.1]
    pos:
      ppos:
        p: [-0.17, 1, 0.042]
      qpos: [0.495, 0.498, 0.503, 0.505]
      randp_scale: [0.15, 0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 1
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  -
    robot_uid: panda-0
    pos:
      ppos:
        p: [-0.8, -0.9, 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-1
    pos:
      ppos:
        p: [-0.8, -0.3, 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-2
    pos:
      ppos:
        p: [-0.8, 0.3, 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  -
    robot_uid: panda-3
    pos:
      ppos:
        p: [-0.8, 0.9, 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: pose
        params: [[0.276124, -0.86324, 0.312292], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent1
      pose:
        type: pose
        params: [[0.278001, -0.213242, 0.312343], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent2
      pose:
        type: pose
        params: [[0.279735, 0.386755, 0.31239], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_agent3
      pose:
        type: pose
        params: [[0.281468, 0.986752, 0.312436], [0.0014413, -0.0973461, 0.000101805, 0.99525]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[0.813265, -0.0209376, 0.481497], [0.00358489, 0.0391521, 0.000140324, -0.999227]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: pose
        params: [[0.868396, 1.09695, 0.703708], [0.454605, 0.234498, 0.125406, -0.85007]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100