# configuration for objects and agents, add scene as well
task_name: StrikeCube
scene:
  name: Table
  primitives:
    - name: cube
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [0.7333333333, 0.4549019608, 0.6862745098, 1.]
        name: cube
        initial_pose:
          p: [0.1, -0.1, 0.02]
      pos:
        ppos:
          p: [0.1, -0.1, 0.02]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.05, 0.2, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]
        
  assets: 
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos: 
        ppos:
          p: [-0.12, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
  env:
    floor_width: 100
    
objects:
  - name: hammer
    file_path: assets/objects/hammer_annotated/base.glb
    annotation_path: assets/objects/hammer_annotated/model_data.json
    material: 
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.
    visual:
      filename: assets/objects/hammer_annotated/base.glb
      scale: [0.079, 0.079, 0.079]
    collision:
      type: convex
      filename: assets/objects/hammer_annotated/base.glb
      scale: [0.079, 0.079, 0.079]
    pos:
      ppos:
        p: [0., 0., 0.042]
      qpos: [0.093, 0.873, 0.476, 0.051]
      randp_scale: [0.06, 0.15, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 0.05
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.1, 0.1, 0.1]

agents:
  - 
    robot_uid: panda-0
    pos:
      ppos:
        p: [-0.615, 0., 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.5707963268, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera
      pose:
        type: look_at
        params: [[0.25, 0.5, 0.4], [-0.1, 0, 0.1]]
      width: 512
      height: 512
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[0.6, 0.7, 0.6], [0.0, 0.0, 0.35]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100
