# configuration for objects and agents, add scene as well
task_name: TwoRobotsStackCube
scene:
  name: Table
  primitives:
    - name: goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.11
        thickness: 0.00005  # 1e-5
        name: goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [0.05, 0., 0.001]

      pos:
        ppos:
          p: [0.05, 0., 0.001]
          q: [0., 1.5707963268, 0.]
        qpos: [0., 0.70710678, 0., 0.70710678]
        randp_scale: [0.1, 0., 0.]
        randq_scale: [0., 0., 0., 0.]

    - name: cubeA
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [0.04705882, 0.16470588, 0.62745098, 1.]
        name: cubeA
        initial_pose:
          p: [-0.05, -0.1, 0.02]
      pos:
        ppos:
          p: [-0.05, -0.1, 0.02]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.1, -0.1, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]

    - name: cubeB
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.02
        color: [0, 1, 0, 1]
        name: cubeB
        initial_pose:
          p: [-0.05, 0.1, 0.02]
      pos:
        ppos:
          p: [-0.05, 0.1, 0.02]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.1, 0.1, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]
  assets: 
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos: 
        ppos:
          p: [-0.12, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
  env:
    floor_width: 100

agents:
  - robot_uid: panda-0
    pos:
      ppos:
        p: [0., -0.75, 0.]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  - robot_uid: panda-1
    pos:
      ppos:
        p: [0., 0.75, 0.]
        q: [0., 0., -1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_agent0
      pose:
        type: look_at
        params: [[-0.5, 0.115, 0.4], [0, -0.235, 0.1]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
    - 
      uid: head_camera_agent1
      pose:
        type: look_at
        params: [[0.5, -0.115, 0.4], [0, 0.235, 0.1]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[0.553884, 0.0884931, 0.477073], [0.0190398, 0.183913, 0.00350626, -0.982752]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[1.4, 0.8, 0.75], [0., 0.1, 0.1]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100
